import { uniqueId } from "lodash";
import ManageAccountsIcon from '@mui/icons-material/ManageAccounts';
const Menuitems = [
  {
    id: uniqueId(),
    title: "Dashboard",
    icon: "/images/icons/dashboard.svg", // icon: GridViewOutlinedIcon,
    icon_c: "/images/icons/dashboard_c.svg", // icon: GridViewOutlinedIcon,
    href: "/",
    allowed_type: [1, 2, 3],
    type: 1,
  },
  
  {
    id: uniqueId(),
    title: "Certification",
    icon: "/images/icons/certificate.svg",
    icon_c: "/images/icons/factory_c.svg",
    innerItem:[
      {
        id: uniqueId(),
        title: "Factory",
        icon: "/images/icons/factory.svg",
        icon_c: "/images/icons/factory_c.svg",
        href: "/factory-list",
        related_path: ["/factory-action"],
        allowed_type: [1, 2, 3],
        type: 1,
      },
      {
        id: uniqueId(),
        title: "Certificates",
        icon: "/images/icons/certificate.svg", // icon: GridViewOutlinedIcon,
        icon_c: "/images/icons/certificate_c.svg", // icon: GridViewOutlinedIcon,
        href: "/certificate-list",
        related_path: ["/certificate-action","/certificate-edit"],
        // related_path: ["/certificate-action", "certificate-type-action"],
    
        allowed_type: [1, 2, 3],
        type: 1,
      },
      {
        id: uniqueId(),
        title: "Reports",
        icon: "/images/icons/report.svg", // icon: GridViewOutlinedIcon,
        icon_c: "/images/icons/report_c.svg", // icon: GridViewOutlinedIcon,
        href: "/reports",
        allowed_type: [1, 2, 3],
        type: 1,
      },
    ],
    // href: "/factory-list",
    related_path: ["/factory-action"],
    allowed_type: [1, 2, 3],
    type: 1,
  },
  
  
  
  {
    id: uniqueId(),
    title: "User Management",
    icon: "/images/icons/branch-admin.svg",
    icon_c: "/images/icons/branch-admin_c.svg",
    // href: "/branch-admin",
    // related_path: ["/branch-admin-action"],
    innerItem:[
      {
        id: uniqueId(),
        title: "Guest User",
        icon: "/images/icons/guest-user.svg",
        icon_c: "/images/icons/guest-user_c.svg",
        href: "/guest-user",
        related_path: ["/guest-user-action"],
    
        allowed_type: [1],
        type: 2,
      },
      {
        id: uniqueId(),
        title: "Branch Admin",
        icon: "/images/icons/branch-admin.svg",
        icon_c: "/images/icons/branch-admin_c.svg",
        href: "/branch-admin",
        related_path: ["/branch-admin-action"],
    
        allowed_type: [1],
        type: 2,
      },
      {
        id: uniqueId(),
        title: "Factory Admin",
        icon: "/images/icons/branch-admin.svg",
        icon_c: "/images/icons/branch-admin_c.svg",
        href: "/factory-user",
        related_path: ["/factory-user-action"],
    
        allowed_type: [1],
        type: 2,
      },
    ],
    allowed_type: [1],
    type: 2,
  },
  {
    id: uniqueId(),
    title: "Master Modules",
    icon: "/images/icons/branch.svg",
    icon_c: "/images/icons/branch_c.svg",
    // href: "/branch",
    // related_path: ["/branch-action"],
    innerItem:[
      {
        id: uniqueId(),
        title: "Branch",
        icon: "/images/icons/branch.svg",
        icon_c: "/images/icons/branch_c.svg",
        href: "/branch",
        related_path: ["/branch-action"],
        allowed_type: [1],
        type: 3,
      },
      {
        id: uniqueId(),
        title: "Department",
        icon: "/images/icons/department.svg",
        icon_c: "/images/icons/department_c.svg",
        href: "/department-list",
        related_path: ["/department-action"],
        allowed_type: [1],
        type: 3,
      },
      {
        id: uniqueId(),
        title: "Designation",
        icon: "/images/icons/designation.svg",
        icon_c: "/images/icons/designation_c.svg",
        href: "/designation-list",
        related_path: ["/designation-action"],
        allowed_type: [1],
        type: 3,
      },
      {
        id: uniqueId(),
        title: "Certficate Type",
        icon: "/images/icons/certificate-type.svg",
        icon_c: "/images/icons/certificate-type_c.svg",
        href: "/certficate-type",
        related_path: ["/certificate-type-action"],
        allowed_type: [1],
        type: 3,
      },
      {
        id: uniqueId(),
        title: "Customer",
        icon: "/images/icons/customer.svg",
        icon_c: "/images/icons/customer_c.svg",
        href: "/customer-list",
        related_path: ["/customer-action"],
        allowed_type: [1],
        type: 3,
      },
      {
        id: uniqueId(),
        title: "Product",
        icon: "/images/icons/customer.svg",
        icon_c: "/images/icons/customer_c.svg",
        href: "/product-list",
        related_path: ["/product-action"],
        allowed_type: [1],
        type: 3,
      },
    ],
    allowed_type: [1],
    type: 3,
  },

  
  {
    id: uniqueId(),
    title: "Production",
    icon: "/images/icons/customer.svg",
    icon_c: "/images/icons/customer_c.svg",
    allowed_type: [1],
    innerItem:[
      {
        id: uniqueId(),
        title: "Production Order",
        icon: "/images/icons/customer.svg",
        icon_c: "/images/icons/customer_c.svg",
        href: "/production-order",
        
        related_path: ["/production-order-action"],
        allowed_type: [1],
        type: 5,
      },
      {
        id: uniqueId(),
        title: "Mass Update",
        icon: "/images/icons/customer.svg",
        icon_c: "/images/icons/customer_c.svg",
        href: "/production-order/mass-update",
        related_path: ["/production-order-action"],
        allowed_type: [1],
        type: 5,
      },
      {
        id: uniqueId(),
        title: "Requests",
        icon: "/images/icons/customer.svg",
        icon_c: "/images/icons/customer_c.svg",
        href: "/requests",
        related_path: [],
        allowed_type: [1],
        type: 5,
      },
      {
        id: uniqueId(),
        title: "Under Development",
        icon: "/images/icons/customer.svg",
        icon_c: "/images/icons/customer_c.svg",
        href: "/under-development",
        
        related_path: ["/production-order-action"],
        allowed_type: [1],
        type: 5,
      },
    ],

    type: 3,
  },
  
  // {
  //   id: uniqueId(),
  //   title: "Mass Update",
  //   icon: "/images/icons/customer.svg",
  //   icon_c: "/images/icons/customer_c.svg",
  //   href: "/production-order-mass-update",
  //   related_path: ["/production-order-action"],
  //   allowed_type: [1],
  //   type: 5,
  // },
  // {
  //   id: uniqueId(),
  //   title: "Requests",
  //   icon: "/images/icons/customer.svg",
  //   icon_c: "/images/icons/customer_c.svg",
  //   href: "/requests",
  //   related_path: [],
  //   allowed_type: [1],
  //   type: 5,
  // },

];

export default Menuitems;
